spring:
  cloud:
    application:
      name: discovery-service

server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    region: default
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka
