spring:
  profiles: dev
  application:
    name: users-service

  datasource:
    url: jdbc:postgresql://localhost:5477/userdb
    username: toolalaMicroservice
    password: admin123
    driver-class-name: org.postgresql.Driver
    testWhileIdle: true
    validationQuery: SELECT 1 FROM DUAL
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

server:
  port: 3001