server:
  port: 7070
  context-path: /

spring:
  application:
    name: zuul-gateway

zuul:
  sensitive-headers: Cookie,Set-Cookie,Authorization
  retryable: true
  routes:
    users-service:
      path: /api/users-service/**
      service-id: users-service
      strip-prefix: true

security:
  # disable spring boot basic authentication
  basic:
    enable: false
  ignored: /users/activator, /uaa, /health, /info

logging:
  level: org.springframework.security: DEBUG

ribbon:
  connectTimeout: 20000
  readTimeout: 20000

