spring:
  profiles:
    active: native

  cloud:
    config:
      server:
        git:
          uri: https://github.com/MMICHIELI/first.git
        native:
          search-locations: classpath:/config/{profile}