#spring:
#
#  cloud:
#    config:
#      server:
#        native:
#          search-locations: classpath:/config/{profile}

#eureka:
#  client:
#    region: default
#    registry-fetch-interval-seconds: 5
#    service-url:
#      defaultZone: http://localhost:8761/eureka/