spring:
  profiles:
    active: native

  cloud:
    config:
      server:
        git:
          uri: https://github.com/MMICHIELI/first.git

eureka:
  client:
    region: default
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
