spring:
  profiles:
    active: native

  cloud:
    config:
      server:
        git:
          uri: D:\Dev\Workspaces\Apps\MicroServices\first-microservices\config-service\src\main\resources\config
        native:
          search-locations: classpath:./config/{profile}
