spring:
  profiles:
    active: native

  cloud:
    config:
      server:
        git:
          uri: https://github.com/MMICHIELI/first/tree/feature/discovery-service
        native:
          search-locations: classpath:/config/{profile}
